### ISSUE TITLE
1.2.0 changelog/wishlist

### ISSUE THREAD

**Issue by Eluinhost** [Eluinhost/UHC#81]
Chanelog item / PR
- [x] Notch apple recipe in 1.9+ / #88 
- [x] Fix being able to 'delete' 0 stack items in the /uhc inventory (still breaks but doesn't affect other people and running /uhc brings them back again) #100 
- [x] Add automatic update checker that notifies when new downloads are available via github #97 
- [ ] Tab list timer render #91 
- [ ] Death bans unwhitelist action #87 
- [ ] Death bans bypass permission #87 
- [ ] Potion restriction rework / #80
- [x] Fix for horse armour disable inversion on mount / #103  
- [ ] Timer flag for repeated timers
- [ ] Ability to hide modules from the /uhc inventory
- [ ] 'rules' inventories with configurable contents
- [ ] Full hosting tutorial for 1.9+?

**Comment by Eluinhost** [comment]
This release is going to be targeted at 1.9 related updates. @D4mnX + any others let me know if there is anything you want added

**Comment by ghost** [comment]
Just randomly off the bat and my mind right now:
- Shield cooldown control with extensible configuration (similiar to #80)
- Ability to load modules but not have them in the addon inventory (only accessible from commands)
- Modification of module iconstack types via configuration
- "Text only" custom modules via configuration for rules/basic information/similiar?

Do you want me to open up an issue for every idea or keep it to here?

**Comment by Eluinhost** [comment]
@D4mnX 

> Shield cooldown control with extensible configuration

What does this mean, is this a vanilla concept, easily doable?

> Ability to load modules but not have them in the addon inventory (only accessible from commands)

Hidden modules? Pretty easy to do and simple to set up, I'll add it

> Modification of module iconstack types via configuration

Might get a little hairy with disableable modules that switch but it can be overrideable I guess so worth looking into

> "Text only" custom modules via configuration for rules/basic information/similiar

Would it not be worth just storing a separate inventory for this? Would simplify a lot of things, we could even setup a command to load a specific inventory from the config

**Comment by ghost** [comment]
> [snip]
> 
> > What does this mean, is this a vanilla concept, easily doable?

I can't really explain this in text, so here's a potential configuration file instead:

```
shieldstun:
    # This would stun a player's shield for half a second more when damaged with damage cause ENTITY_ATTACK
  - cause: ENTITY_ATTACK
    time: +10
  # This would set a player's shield cooldown to exactly 4 seconds whenever hit by an arrow shot by another player
  - damager: ARROW
    shooter: PLAYER
    time: 80
  # This would stun a shield whenever damaged by anything for 3 MORE seconds
  - time: +60
  # This would remove 1 second from axe cooldowns
  - damager: PLAYER
    tool: .*_AXE # Regular expression support for materials?
    time: -20
```

The idea is that every section represents a predicate for an EntityDamageEvent.

> [snip]
> 
> > Would it not be worth just storing a separate inventory for this? Would simplify a lot of things, we could even setup a command to load a specific inventory from the config

A configuration file to bind specific commands to locations and when executed, open a chest at that location as an unmodifiable inventory? That sounds like a nice idea.
